### ISSUE TITLE
NaN and &nbsp;

### ISSUE THREAD

**Issue by damiantje99** [lokenx/plexrequests-meteor#116]
Hi

I have 2 problems at the moment,

1. When I use the Dev branch and enter the api in Sonarr and Couchpotato settings, it will change to NaN after i saved it. The Master branch doesn't have that problem, but I though i'll let you know.

2. In front of many settings, there stands and &nbsp; This is only at the Admin page and not at the user page (where you request stuff).

Do you have any solution for both problems?

Hope to hear from you,

Kind Regards,

Damian

**Comment by lokenx** [comment]
Number 2 is known, but the package isn't mine so I'm not sure if they have a fix for it. We're removing the package in the new version so probably won't be fixed until then.

The first one is new though. However, again that package is going to be removed so I'd rather focus on getting the new version out instead of trying to fix someone else's package.

**Comment by lokenx** [comment]
Duplicate #110
