### ISSUE TITLE
Sonarr Integration

### ISSUE THREAD

**Issue by LindsayCole** [lokenx/plexrequests-meteor#118]
When integrated with Sonarr, and I add a show, I am getting:

"Error: please enable a service"

It adds the show, just doesn't seem to search for episodes and generates the above error.
If I add the show directly from Sonarr, it works fine, searches and finds the missing episodes.

Thanks,

**Comment by lokenx** [comment]
The error message isn't related to Sonarr, it's actually because you don't have either of the notifications options enabled. It is removed in the next version.

Regarding searching for episodes, it's an undocumented API parameter that tells Sonarr to search for stuff immediately which I wasn't aware of at the time. However, it has changed in the new version as well and searches on adding now.
