### ISSUE TITLE
Request button for TV shows does nothing

### ISSUE THREAD

**Issue by JibbsIsMe** [lokenx/plexrequests-meteor#139]
When I search for any TV show, the request button does nothing when I click it. It appears like it's supposed to be a dropdown. There aren't any errors in the console. I've tried with shows I already have, as well as new shows.

Branch: dev
Version: v0.6.15 (latest commit)
OS: Windows
Browser: Chrome or Firefox

![Image](https://cloud.githubusercontent.com/assets/3630698/10836930/1e57e262-7e8a-11e5-930b-3f37a0abfe06.png)

**Comment by ashleytayles** [comment]
Can confirm issue. This happens to me too.

Branch: v0.6
Version: v0.6.15
OS: Windows Server 2012R2
Browser: IE11 and Chrome Version 46.0.2490.80 m

Tried with Rick and Morty as above, and also "Broad City".

**Comment by lokenx** [comment]
Can you guys try selecting an issue with a movie? Seeing if it's related to #138.

Could be the generation of drop downs on Windows.

Confirmed my Windows 7 machines are fine. Seems to be Window 10/Server 2012R2/and probably Windows 8 maybe.

Can you check your chrome dev tools as I mentioned in the other thread if you've Chrome installed?

**Comment by JibbsIsMe** [comment]
Correct, it is the same idea as #138. The dropdown doesn't show up at all, exactly as described in #138. 

I tested in chrome, and I am on Windows 10.

I'll be honest I know very little about Chrome's dev tools. However, I opened the console and tried to open some dropdowns, and the console stayed blank.

**Comment by lokenx** [comment]
OK, merging issues then.

No worries, something must be up with new versions of Windows. The issue is, the request dropdown isn't generated by JS, while the report issues on is--so not sure what's up.

I've confirmed my Server 2012/IE 10 works fine so got to get my hands on Windows 10 so I can look into this.

**Comment by lokenx** [comment]
Refer to #138 for more updates.

**Comment by ashleytayles** [comment]
To add further;

I know very little about JavaScript, but I took a peek at the requestTV.js.

I see a large chunk of the code is reliant on the "approval needed" variable in the settings, so I tried reproducing with this in both states and it is the same regardless of this setting.

I also took a misguided hunch and tried with the "check user limit" section commented out.. no change.

I can request a movie just fine, the button does it's little animation and it is added to Couchpotato. However nothing happens when clicking request on a TV Show.

**Comment by lokenx** [comment]
Wrong place! You want the [item.js](https://github.com/lokenx/plexrequests-meteor/blob/dev/client/templates/search/item.html) file. For the request button it's straight HTML, just expressions to determine if it's a requested show, or movie/tv show.

````
{{#if isTV}}
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-primary-outline dropdown-toggle tv-request" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-plus"></i> &nbsp; Request
    </button>
    <div class="dropdown-menu">
      <a class="dropdown-item add-request" href="#" value="false">Request New Episodes</a>
      <a class="dropdown-item add-request" href="#" value="true">Request All Episodes</a>
    </div>
  </div>
{{else}}
  <button class="btn btn-primary-outline add-request"><i class="fa fa-plus"></i> &nbsp; Request</button>
{{/if}}
````
