### ISSUE TITLE
Error: ETIMEDOUT - error getting IMDB

### ISSUE THREAD

**Issue by dualznz** [lokenx/plexrequests-meteor#166]
hi i seem to be getting this issue when people request movies through imdb http://i.imgur.com/xjHz6yX.png

Sometimes they have to click it 3 or 4 times to pass it.

Not sure why it is doing this

**Comment by lokenx** [comment]
It's having trouble getting the IMDB ID from TheMovieDB. Because it goes through after another try, it appears maybe the API limit is getting hit.

I've added a new error throw that will hopefully make the errors more useful (at least for me). Just restart your app to get it. How many users do you have using the app?

**Comment by dualznz** [comment]
about 60 people

**Comment by lokenx** [comment]
Hmm I'm going to have a look into the API limits. Wasn't an issue before, but now the images are coming from them too so may need to cache or keep local copies or something.

Thanks for letting me know!

**Comment by dualznz** [comment]
no problem, also in .meteor i dont see \local\db\ so  i cant backup, but not a biggy

**Comment by lokenx** [comment]
Are you running your own MongoDB instance that PR is using? Did you check hidden folders/files?

**Comment by lokenx** [comment]
I don't think it's API limiting, unless multiple people in the same house hold maybe doing tons at once?

> Our current limits are 40 requests every 10 seconds and are limited by IP address, not API key.
