### ISSUE TITLE
Adding movies already existing, should have an extra dialog to report an issue

### ISSUE THREAD

**Issue by keithah** [lokenx/plexrequests-meteor#174]
I love .6 so much! But my Requests is now full of movies already requested, because the current workflow is:
Add movie name, click request, changes to green, THEN the textbox of 'already on Plex' pops up. 

So now I have a movie in the requests list that I have in my db and not sure why someone requested it..

Ideally it would pop up something that says 'this is already in the db, are you sure you want to add, or report an issue?' then have them be able to select the problem with it. Or even just default to 'report an issue, and dont even let them add stuff already added?

Thanks!

**Comment by lokenx** [comment]
If the movie isn't in the PlexRequests database, I can't 

> default to 'report an issue, and dont even let them add stuff already added

as I don't know that until it's been requested and we do the checks. That's why we let the request go through so that future requests don't go through from other users.

Most likely reason is they didn't know it was already there, heck I don't even know half the stuff I have. I don't want to flat out refuse requests that are already in Plex. Even adding the option to report an issue instead of requesting it, requires it to be added to the PlexRequests database and show up in the list.

Now issue handling will change and become more useful, currently I just wanted to get it in ASAP but thinking of ways to make it more useful. If we didn't do issue handling, or separated it from the requests database then it's possible to change what happens when someone requests something that already exists.

**Comment by keithah** [comment]
Understandable. What I'm hoping for is after you do the add to the database, when the file already exists it asks if you're having an issue with the file and set something, or just disregard it because it's already added? 

I'm completely fine with having it add to the db, I just assume exactly what you thought, they didnt know it was there when adding, OR theres an issue with it so theyre reporting it.

**Comment by lokenx** [comment]
I think once I move issues out, there'll be a way to post issues right from the search results. The current request behaviour will stay, but users will be able to create issues without requesting content so help with this. #129 is the ticket for issues, so I shall close this one and track issue reporting changes in there.

**Comment by maxinux** [comment]
Agreed, today adding the same video that already exists to the queue is just broken.  Should be something like:
1. user searches the video
2. if movie exist -> prompt for issues with it, do not add to a queue 
if tv show exists but not the entire series offer only to download the missing episodes
3. add an option to both cases for 'video has errors, try new rip'

**Comment by lokenx** [comment]
There will be a report issue as well as request button for searches once Issues is moved to it's own thing entirely.

Regarding TV shows, can't currently do that as not doing granular type adding, but follow #121 for that.
