### ISSUE TITLE
[Request] Approve only tv shows

### ISSUE THREAD

**Issue by markisoke** [lokenx/plexrequests-meteor#186]
It is great that we now can approve tv shows and movies, but I'd like to see the option to approve only tv shows or only movies. I'd like to have my movies downloaded right away, but I don't want the user give the ability to automaticly download a whole tv show.

**Comment by Drewster727** [comment]
+1

**Comment by markisoke** [comment]
Any news about this feature?

**Comment by only1alive** [comment]
+1. I came here to request this feature. TV shows can suck up a lot of disk space. Had a nephew (doesn't know better) request something with 14+ seasons...ouch!

**Comment by zerorl985** [comment]
+1

**Comment by markisoke** [comment]
Any news here, 4 months later.

**Comment by rigrassm** [comment]
@markisoke, if you would like it done faster you could always jump in and do it yourself, the source is right there.

**Comment by markisoke** [comment]
@rigrassm What a stupid answer, if I could code it myself I would have done it myself and upload it. I wouldn't asking if I could, but unfortunately I can't. So if you don't have anything positive to add to this issue than please shut up. If you have the time to write such stupid comments you could also code this function yourself.

**Comment by rigrassm** [comment]
@markisoke don't come in here with your condescending attitude acting like the maintainer somehow owes you anything more than what he's delivered already. 

It's no one's fault but your own you can't add this feature in yourself, if you can't be bothered to either A) Not be a douche bag internet tough guy and ask for an update politely or B) take the time to learn what you need to so you can add what you seem to think is a trivial function to the project then could you please just sit back and shut your mouth. I actually have contributed(and I had never wrote a line of JavaScript before this) to the project and am actively working on adding new features, what have you done? Nothing? OK then, sit back, shut up, and be thankful others are willingly giving you a product they helped create in their spare time at no cost to you.

**Comment by tedrock** [comment]
Exactly why I subscribed to this, to get notifications of two guys shaking their dicks at each other over the internet. Grow the fuck up both of you.

**Comment by lokenx** [comment]
So, hi. Let's calm down please and thank you!

Yes, I do apologize this hasn't been implemented yet. Personally I don't have nearly as much time to work on this. Most of the work was done while I was off work with a broken knee. It's hard to juggle full time work and side projects.

The reason this wasn't added to begin with was due to db issues as it would need to be changed. I did implement this in a new non-meteor version of the app, however that version currently doesn't have a front end or downloader integration. We can now do basic db migrations so we'll either add it to this one, or complete work on the fork.

Keep in mind, that in the grand scheme of things this isn't that big of a feature, I'd rather spend time figuring out the music/headphones integration. Those guys have been waiting for ages, and politely might I add.

**Comment by lokenx** [comment]
There's a branch that has this change, will merge once I check a few more things.

I also need to figure out how to make a notice for the admins for this as it'll default to not requiring approvals for both requests until you make a change.

Although I may reverse it so that it does require approvals so people can't spam you with crazy by accident.

**Comment by markisoke** [comment]
Thank you very much. This will help a lot!
