### ISSUE TITLE
error	Error getting TVDB ID, none found!

### ISSUE THREAD

**Issue by whitecollar17** [lokenx/plexrequests-meteor#210]
When i try to add the serie: "Making a Murderer (2015)" the status button is 10 minuts on "Requesting..."

In the error log: error	Error getting TVDB ID, none found!

And the serie is not add on Sonarr :(

**Comment by damiantje99** [comment]
I'm getting the same error when i'm requesting that show. I don't think its an Plex Request Issue because I don't have any problems with requesting other shows/movies. I guess you can also request other shows successfully. I can however add the show in Sonarr directly. Maybe thats a good workaround.

**Comment by lokenx** [comment]
It's mostly likely due to The Movie DB not having the TVDB ID for the show. Next version will use the TVDB new API so this won't be an issue going forward.

For now you'll have to contribute to The Movie DB to get this TVDB ID added to their dB.
