### ISSUE TITLE
[Request] User Notifications

### ISSUE THREAD

**Issue by grokdesigns** [lokenx/plexrequests-meteor#218]
It would be awesome if users could be notified when something they requested is available or approved. The way I envision it is after the user logs in with their username, their email address is stored somewhere (pulled from https://plex.tv/pms/friends/all?X-Plex-Token="SERVERTOKEN") and they can set up notification options for their account (Send Email When Request is Available, Send PushBullet When Request Approved, etc.).

**Comment by lokenx** [comment]
I'm looking at moving to full user accounts for your shared users to allow easier ability of stuff like this, something is in the works!

**Comment by thinktwo** [comment]
I would also love for users to be able to setup notifications for a selection of tv-shows to pushbullet/pushover when new episodes are available.

**Comment by lokenx** [comment]
@thinktwo that would be cool, but beyond the scope of the app currently unfortunately. However, once I've figured out the new user system I can see how things could work.

**Comment by zetas** [comment]
I was just about to start working on this but it looks like the codebase is in quite a bit of flux. @lokenx please post here or contact me via email with some details. I'd like to add this feature for my users and I'm well versed in nodejs and I can probably pickup meteor pretty quickly.

**Comment by lokenx** [comment]
I'm actually migrating to NodeJS/Hapi backend over [here](https://github.com/lokenx/plex-requests) so your time may be better spent over there.

It's still early stages: have most of the end points configured and authentication completed (but I'm still mulling changes regarding this for example using the Plex token to obtain the admin user and create their account instead of local admin). Also having tied in the various services yet but I may move that logic into separate npm packages if they don't exist and hook in them where appropriate.

Maybe open an issue over there with what you want to work on!

**Comment by rigrassm** [comment]
I have a pull request open that addresses this to some degree. I added the ability to send pushbullet Notifications to channels. You can have users subscribe to the channel and they will receive notifications when they're sent out.

My pull request should go through soon so keep an eye out.

**Comment by rigrassm** [comment]
The latest version of plex requests allows the admin to push notifications to a custom Pushbullet channel that your users can then subscribe to. Once setup and the users are subscribed, they will get a notification anytime a request is approved. 

Keep in mind all those subscribed to the channel will get notifications for all approved content not just their own.
