### ISSUE TITLE
Sonarr Profiles

### ISSUE THREAD

**Issue by lokenx** [lokenx/plexrequests-meteor#286]
Stop the method being called if Sonarr is not configured. Maybe make it a button in the settings to call the method. It's filling up logs needlessly.

**Comment by lokenx** [comment]
Can you give [sonarr-profiles](https://github.com/lokenx/plexrequests-meteor/tree/sonarr-profiles) branch a try @rigrassm

**Comment by rigrassm** [comment]
Just did and it worked as expected. I would change a couple things now that I've gone through it again though.

1. move the test sonarr button to the very bottom
2. Set the default server ip to 127.0.0.1( since its likely on the same server)
3. Maybe hide the get profiles until sonarr is enabled and have that option show up at the top right below the enable sonarr checkbox.

Just some thoughts I wanted to jot down while I was messing with this section.

Everything seems to be in working order though and I'd say safe to merge.

**Comment by lokenx** [comment]
OK sweet!

I'd say make new branch/issue for those, because it could probably be extended to SickRage/CouchPotato.

1. Sure
2. Sure
3. Seems superfluous. If you don't use Sonarr you're probably not going to that pane nor scroll down the page to the button
