### ISSUE TITLE
[Error] Method TVMAZESearch undefined

### ISSUE THREAD

**Issue by pairughdocks** [lokenx/plexrequests-meteor#325]
Every TV show I search is coming up with this error, Modern Family, Workaholics, etc... I've updated to the latest version and no TV Show updates were found.

**Comment by rigrassm** [comment]
You aren't running the latest version then. That method calls name was changed quite a few updates back.

What platform are you on and how did you update?

**Comment by lokenx** [comment]
It's possible the version/packages files got out of sync (it happens when updates happen locally and git doesn't pull down correct changes).

What's the result of a `git status` in the project folder?

**Comment by pairughdocks** [comment]
I just ran meteor update. It's been working fine up until a few days ago. I'll re-pull and see what happens. Thanks!

**Comment by rigrassm** [comment]
Thats the issue, meteor update only updates meteor and package versions within the application. Once you do the git pull it will be fixed.

Make sure to backup the .meteor/local/db folder just in case something goes wrong.

**Comment by rigrassm** [comment]
The solution here is to update to the current version of Plex requests. That's going to be the solution as that method call is not available so it will error out every time. It's as simple as doing a `git pull` to get caught up.

Going to close the ticket now since there hasnt been an update on whether the options given have worked in 2 weeks. @pairughdocks feel free to comment here if you still have the issue and I will reopen the ticket.
