### ISSUE TITLE
[Request] FreeBSD daemon at start up

### ISSUE THREAD

**Issue by tonyp1983** [lokenx/plexrequests-meteor#350]
Absolutely loving plexrequests and the ease of use. Only thing that's missing for me is that I'm running it from FreeBSD and cannot figure out how to get this running as daemon at startup using an rc.d script. I've looked up some basic rc.d scripts but can't work out how I execute plexrequests without being in the directory.

This would really make my life so much easier. :)

**Comment by rigrassm** [comment]
I worked on this a bit but since I dont have a machine running BSD and all my others are using Sytemd(which makes this so much easier lol) I asnt able to do any extensive testing. I was able to get an init script that could start the program correctly but was never able to get it to be able to have it stop it(using the conventional methods for rc.d scripts). You could hack together something that starts the application and the manually retrieves the PID's and writes them to a file so that when you run the stop function it just kills those PID's but I'm not sure thats the best way to go about it,

Unfortunately this isnt so much an issue with plexrequests as it is a meteor/freeBSD one. If it were me I would check out their respective forums and see if they have any advice on how to move forward.

If you do get a working init-script, feel free to create a pull request and we'll add it in so others have access to it as well.

**Comment by UnR34L** [comment]
I don't want to hijack this issue but can you explain or atleast point me in the right direction as to how to get plexrequests running on FreeBSD.

Up untill now I thought it wasn't even possible.

Cheers.

**Comment by tonyp1983** [comment]
@UnR34L it took a bit of Googling to get Meteor setup and needed so hunting around for some individual components Meteor needed. I don't remember exactly what I did or where things came from but I believe this was where I started and then used the error messages I encountered trying to start plexrequests to Google around and fix what didn't work) I then cobbled together a very inelegant rc.d script to daemonise startup of plexrequests (I can send you it if you need it). I actually set everything up in a jail under FreeNAS 9.10 (FreeBSD 10.3).

**Comment by rigrassm** [comment]
Closing due to age and the issue being related to running meteor and not the Plexrequests application.
