### ISSUE TITLE
[Feature Request] Calendar Page / View to track new TV Shows

### ISSUE THREAD

**Issue by AngryNoodlez** [lokenx/plexrequests-meteor#379]
Hi,

First of all, I absolutely love PlexRequests - Thanks for all the brilliant work you do!

I have a relatively large user base, most of which utilize PlexRequests on an almost daily basis.

What would be awesome (if possible) is a calendar page similar to the one Sonarr provides, where you can view upcoming/past released TV Shows, along with their download status.

I currently utilize the iCal feature in Sonarr and pull this information on a custom page that I've added to the navbar. However, it's not the prettiest - and obviously requires me to re-add it every time I update!

Let me know what you think :-)

~Mat

**Comment by rigrassm** [comment]
Going to have to mark this one as out of scope since monitoring episodes air dates is not something that falls under Plexrequests umbrella. As you mentioned, this is already something that's implemented by Sonarr, whose platform is designed for delivering this sort of product, and I don't see it being possible to improve on what they are able to deliver.

I would reach out to the Sonarr team and see about the possibility of making it easier to hook into the calendar data (RSS feed comes to mind). If you're able to get a good little application put together I'll definitely be a user!
