### ISSUE TITLE
Can you search for items that have not yet aired?

### ISSUE THREAD

**Issue by chadberg** [lokenx/plexrequests-meteor#401]
A user of mine tried to request Berlin Station, a show that isn't yet airing, but will soon, and is listed in TMDB... https://www.themoviedb.org/tv/66282-berlin-station but no search results came up. I confirmed that in my testing.

**Comment by rigrassm** [comment]
Hmm, that's odd. It should pull up. We use tvmaze.com's api and it returns
the show as the first item in the response. May need to revisit the api
module and see if there were any api changes of if there is something
blocking the result.

I'll take a look at it this weekend and see what's going on with it.

## API check
-- http://api.tvmaze.com/search/shows?q=berlin%20station

**Returns**
```
[{"score":2.553552,"show":{"id":2632,"url":"
http://www.tvmaze.com/shows/2632/berlin-station","name":"Berlin
Station","type":"Scripted","language":"English","genres":["Drama","Mystery","Espionage"],"status":"In
Development","runtime":60,"premiered":"2016-10-16","schedule":{"time":"21:00","days":["Sunday"]},"rating":{"average":null},"weight":2,"network":{"id":253,"name":"Epix","country":{"name":"United
States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":50191,"thetvdb":null,"imdb":null},"image":{"medium":"
http://tvmazecdn.com/uploads/images/medium_portrait/70/175826.jpg
","original":"
http://tvmazecdn.com/uploads/images/original_untouched/70/175826.jpg"},"summary":"<p><strong><em>\"Berlin
Station\"</em></strong> follows Daniel Miller, a newly anointed case
officer who has arrived at the CIA foreign station in Berlin, Germany. It
with a clandestine mission: to uncover the source of a leak who has
supplied information to a now-famous whistleblower named \"Thomas Shaw.\"
Guided by jaded veteran Hector DeJean, Daniel learns to contend with the
rough-and-tumble world of the field agent—agent-running, deception, the
dangers and moral compromises. As he dives deeper into the German capital's
hall of mirrors and uncovers the threads of a conspiracy that leads back to
Washington, Daniel wonders: Can anyone ever be the same after a posting to
Berlin?</p>","updated":1471847188,"_links":{"self":{"href":"
http://api.tvmaze.com/shows/2632"},"nextepisode":{"href":"
http://api.tvmaze.com/episodes/881132"}}}}]
```

**Comment by chadberg** [comment]
Hmm. I thought from the FAQ page that TMDB was used, not tvmaze. Regardless, the behavior is the same.

**Comment by rigrassm** [comment]
We do use TMDB for searching movies, off the top of my head I believe we
also send the tmdb id's of TV shows to the download
clients(sickrage/sonarr).

We switched a while back to TVMaze since its API was open(no token
required) and its search function returned much more accurate results. This
doesn't look like a TVMaze issue though, something is causing that result
to get parsed out.

**Comment by lokenx** [comment]
It's not getting picked up because it doesn't have a TVDB ID within TVMaze which means SickRage/Sonarr can't add it as they rely on that ID I believe. Once a TVDB ID gets added it'll appear in search results.

Not sure how TV Maze gets updated but if it's open to the public you could submit the TVDB and then the API would return it and it would show up!
