### ISSUE TITLE
Requesting two shows of the same name from different years ends up in the same folder in Sonarr

### ISSUE THREAD

**Issue by Cheezykins** [lokenx/plexrequests-meteor#423]
When requesting two shows of the same name but different years, requests is adding them to Sonarr using the same folder name.

For example adding The Flash (1990) and The Flash (2014) results in both shows being added to Sonarr, except with the same folder name of The Flash. Adding Lost and Lost (2004) and Lost (2001) results in both shows being added with a folder called Lost. It's like it's stripping the year from the folder name.

When they start appearing, the folder ends up muddled up with both shows episodes coexisting.

[edit] This is running on Ubuntu Server 16.04 using Meteor 1.4.2.3 and an up to date clone of master.

**Comment by rigrassm** [comment]
This is an issue with Sonarr as PlexRequests doesn't have any control over the naming of content. 

Look at the "Media Management" settings section in Sonarr (Click show advanced for all options) to configure folder naming schemes and settings.

**Comment by Cheezykins** [comment]
I disagree that this is Sonarr's responsibility.

Here's what's shown in Plex Requests after searching for Lost:
![Image](http://i.imgur.com/6MC7fTk.png)

And Sonarr for the same:
![Sonarr Image](http://i.imgur.com/v6yPO8W.png)

As you can see, both include the year, when requested, here is what Plex Requests sends in the post request to Sonarr:

```json
{
  "tvdbId": 72906,
  "title": "Lost",
  "qualityProfileId": 1,
  "seasons": [],
  "seasonFolder": true,
  "rootFolderPath": "/mnt/storage/Media/TV",
  "addOptions": {
    "ignoreEpisodesWithFiles": true,
    "ignoreEpisodesWithoutFiles": true,
    "searchForMissingEpisodes": false
  },
  "images": []
}
```

Vs the same for Sonarr:

```json
{
  "title": "Lost (2001)",
  "sortTitle": "lost 2001",
  "seasonCount": 1,
  "status": "ended",
  "overview": "Three pairs of globe-trotting strangers must work together to be the first team to reach the Statue of Liberty from a secret drop location. The winners will split the prize of $200,000. Over the life of the series, two different adventures were scheduled to take place.",
  "network": "NBC",
  "images": [
    {
      "coverType": "fanart",
      "url": "http://thetvdb.com/banners/fanart/original/72906-1.jpg"
    },
    {
      "coverType": "banner",
      "url": "http://thetvdb.com/banners/graphical/72906-g.jpg"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "monitored": true
    }
  ],
  "year": 2001,
  "profileId": "1",
  "seasonFolder": true,
  "monitored": true,
  "useSceneNumbering": false,
  "runtime": 60,
  "tvdbId": 72906,
  "tvRageId": 0,
  "tvMazeId": 17377,
  "firstAired": "2001-08-31T23:00:00Z",
  "seriesType": "standard",
  "cleanTitle": "lost2001",
  "titleSlug": "lost-2001",
  "genres": [
    "Reality"
  ],
  "tags": [],
  "added": "0001-01-01T00:00:00Z",
  "ratings": {
    "votes": 4,
    "value": 5.3
  },
  "qualityProfileId": 0,
  "episodeFileCount": 0,
  "episodeCount": 0,
  "isExisting": false,
  "rootFolderPath": "/mnt/dorgin1/TV/",
  "addOptions": {
    "ignoreEpisodesWithFiles": false,
    "ignoreEpisodesWithoutFiles": false,
    "searchForMissingEpisodes": false
  }
}
```

Sonarr is clearly making a judgement call about the title and deciding to include the year.

I note that Plex Requests currently does a check of all series for the tvdbid to see if the show already exists. Maybe as that iterates through allShows.data in seriesStats() in sonarr.js, it could also check if a show with the proposed title exists with a different tvdbid and if so, adds the year to the new show name in brackets. That way you wont have shows ending up in the same folder.

I did start on a PR for this, but I have zero experience with Meteor apps, and you guys can probably work it out better than I, plus whatever is done would probably have to be implemented for Sickrage too, and I have no dev environment set up for that or knowledge of it.

**Comment by rigrassm** [comment]
I agree that the series folder name should include the year that the series was first aired, the issue here is that Sonarr should not just arbitrarily accept the series title as is and then proceed to set the folder name based on that submission. In fact, since the API requires a TVDB id be submitted when adding a series, they should be using the values returned from querying against that service and not leave it up to a client application. They make the assumption that the year is included with the title knowing full well that the application making the API call may not follow this convention.

The Sonarr API should be using it's own internal methods for obtaining the necessary data needed for adding the series unless explicitly defined in the API call itself. There are numerous issues on the projects github that would be solved if they were to implement this behavior.

https://github.com/Sonarr/Sonarr/issues/393
https://github.com/Sonarr/Sonarr/issues/1017
https://github.com/Sonarr/Sonarr/issues/1403

It's Sonarrs job to handle the organization of media and therefor their responsibility to ensure that two completely different series don't end up using the same folder. This is definitely a bug and it should be filed with Sonarr, there is absolutely no reason two different series that have two different TVDB ID's should end up using the same path on the filesystem.

**Comment by markus101** [comment]
I'm not sure how 393 and 1017 apply here, they aren't related to the API.

Currently the title is a mandatory field when adding a series (https://github.com/Sonarr/Sonarr/wiki/Series#post), you can send back the whole object from the series lookup endpoint (https://github.com/Sonarr/Sonarr/wiki/Series-Lookup) along with the settings required to add the series. This is something we'll be looking at addressing (since not trusting the client is generally a good idea).

It looks like we don't validate the folder name isn't going to be a duplicate when adding a series which is definitely a bug on our end.
