### ISSUE TITLE
Requesting a TV show doesn't tell Sonarr to search for it

### ISSUE THREAD

**Issue by mattenz** [lokenx/plexrequests-meteor#424]
Quite possible I have something misconfigured however whenever users add a request for a show, when the show is sent to Sonarr it successfully adds the show however it doesn't set the show as monitored and doesn't search for the show to download episodes.  Instead, I have to manually go to Sonarr and do these tasks.  Is this changeable or a limitation of Sonarr?

**Comment by rigrassm** [comment]
If the user selects the "New Episodes" option when requesting the series then the API call to Sonarr is sent with the Search for missing episodes flag set to false(since we only want episodes that come after the time of the request). When they select the all episodes option this flag is set to true and will trigger a search. 

I haven't had the time to dive into it but eventually I plan to add more fine tuned control of the episodes/seasons being requested. As it's designed now though, Sonarr should be running the search if your request is for all episodes. If it's not you may want to check your Sonarr logs and file an issue with the Sonarr devs if it's not behaving correctly.
