### ISSUE TITLE
Remove "Register" from Admin page

### ISSUE THREAD

**Issue by ciehanski** [lokenx/plexrequests-meteor#446]
After the first initialization and setup of PlexRequests, why do we need a "register" button on the admin page? My instance is running on a public webserver because I have some remote buddies who use my Plex server, so PlexRequests is exposed. I was able to create a dummy admin account and access the admin settings....Is there anyway to prevent this from happening?

**Comment by rigrassm** [comment]
I'll look into having the link removed after the admin account is created. 

That said, once the admin account is created, you will not be able to create another one after that. It's recommended that you configure at least this part before opening up access to the outside world.

**Comment by jrdnlc** [comment]
I believe this was fixed. It doesn't let me create another admin after i created mine but it would be good to remove the Register part from the page. @rigrassm

**Comment by rigrassm** [comment]
Yeah, I have looked into this and that page is actually auto-generated and there are, unfortunately, not any methods for removing it that don't involve some hacky CSS modifications that just hide the line.

Gonna close this issue out as won't fix but only because it's a platform issue and mostly out of our hands.
