### ISSUE TITLE
Approving movie to Radarr getting "match error"

### ISSUE THREAD

**Issue by tiddles155** [lokenx/plexrequests-meteor#453]
Approving movie to Radarr getting "match error: Expected String, got undefined"?

updated to latest release 1.20.2? any ideas guys?

**Comment by jeradM** [comment]
It looks like this is due to request.year being undefined and failing the check in radarrMethods.js

**Comment by jeradM** [comment]
I was having the same problem so I looked at this a little closer at this and the seems to be that when `insertMovie()` is called, the `year` request param is not saved so it is undefined when trying to approve the request and the check fails. This doesn't happen when approval isn't required since the params are passed directly to `radarrMovieAdd()`. I was able to solve this by adding an optional `year` field to the collection and storing the year param in `insertMovie()`.

**Comment by rigrassm** [comment]
Mind submitting a pull request for this?

**Comment by jeradM** [comment]
Not at all. Just submitted

**Comment by lokenx** [comment]
#459

**Comment by ohmar** [comment]
I'm still seeing this issue on 1.20.3. Movies are approved and sent to Radarr when approval isn't required but fail when it is required.

**Comment by ohmar** [comment]
FYI this appears to be resolved in the latest update. Thank you!
