### ISSUE TITLE
Admin link CSS issue

### ISSUE THREAD

**Issue by tarnecki** [lokenx/plexrequests-meteor#472]
Hi,
currently admin link is showing to all visitors.
I've updated .CSS to hide it but got wiped by restart - i'm guessing there's a reason why when the service is being restarted it downloads all files / setup from net again?
I really do not want people to see admin link - i prefer going to the hard url :)
can you advise please how to either add extra .CSS and connect to the site or who to edit without wiping .CSS after each reboot? Thanks.

**Comment by AngryNoodlez** [comment]
Hi,

You can edit /client/templates/layout/layout.html line 8

Change

    <a class="navbar-brand admin-link" href="{{pathFor 'admin.page'}}">Admin</a>

to
    {{#if currentUser}}
    <a class="navbar-brand admin-link" href="{{pathFor 'admin.page'}}">Admin</a>
    {{/if}}


This will display the Admin link only when signed in as Admin. You can also just remove this line to remove the admin button altogether. This won't get wiped during restarting the application, but it will if you overwrite the files when updating to a later version.

Let me know if you have any problems with this, I've heavily customized my Plexrequests-Meteor installation.

**Comment by tarnecki** [comment]
thank you very much 💃

**Comment by tarnecki** [comment]
the only issue i have is the not updating added / requested tv shows .... cant tick it manually as available and it doesn't count added episodes.

**Comment by lokenx** [comment]
Yeah we show it because otherwise initial install wouldn't know it's there. Regardless, as long as you've got a login to it, no one can create another account (even though it shows register it will fail).

We look to SickRage or Sonarr for episode counts, if neither of those are configured we don't update those fields. If you've issues with that still open an issue for it specifically!
