### ISSUE TITLE
Iron:Router Issue NGINX Reverse Proxy

### ISSUE THREAD

**Issue by pairughdocks** [lokenx/plexrequests-meteor#482]
Hello all,

If I visit my PlexRequest site from a phone, tablet, etc.. I am greeted with my landing page. If I hit it from a workstation, I get the Iron:Router no routes defined page. I've attached my NGINX config and Proxy.conf (used with NGINX config) as a paste bin for easy review. All of my other proxied resources work without issue. I am using subdomains

Assumptions:

1. NGINX and PlexRequests are not on the same server
2, NGINX is hosted on a VPS
3. PlexRequests is hosted on a local connection 
4. If I go to http://plexrequestsIP:3000 I get the default landing page
5. If I go to http://request.mysite.com I get the Iron:Router page

Hoping someone can help out and find my mistake. 

Config: https://pastebin.com/J0sfnTAH

**Comment by pairughdocks** [comment]
bump

**Comment by pairughdocks** [comment]
bump^2

**Comment by pairughdocks** [comment]
bump^3

Just looking for some info on how to add the "route" with iron:router.

**Comment by rigrassm** [comment]
There is no route that you need to add, there's something wrong with the proxy configuration that is causing this.

Below are the proxy directives I'm using on my personal server, granted it's hosted on the same server as Plexrequests.

https://paste.fedoraproject.org/paste/EVDI4lz16Xi9ahkzkqKruA

You may try setting the IP address instead of the domain name in your proxy_pass to see if that makes a difference.

**Comment by pairughdocks** [comment]
It looks like it's picking up "location /" in the nginx config, can I please see your stanza in regards to plexrequests? I've applied the proxy config, but have had no change. Thanks @rigrassm

**Comment by rigrassm** [comment]
I use a fairly complex configuration but you're free to take a look at it.

https://paste.fedoraproject.org/paste/gtsMjR2LYVzE56~jFIYX5Q

**Comment by rigrassm** [comment]
Any update on this? If you still need some help let me know, otherwise i'm going to close the issue.
