### ISSUE TITLE
Add NzbGet download status info

### ISSUE THREAD

**Issue by camjac251** [lokenx/plexrequests-meteor#51]
It would be cool if users could see their requested item's download status.

**Comment by lokenx** [comment]
I'm assuming for TV shows? We decided for now to not provide status of TV shows like movies because of the nature of TV shows: what constitutes downloaded?

A movie is either available or not, there's no in between. For TV, what season is done, what episode is done, what season or episode does a specific user care about versus other users. If a show is currently and you don't download the latest episode instantly, is it marked as done or not? What if you only have one season, but not he rest, is that done or not? I we can come up with a way to make this distinction that doesn't involve constant API calls and constant changes we can do it, but for now it is what it is.
