### ISSUE TITLE
cool project

### ISSUE THREAD

**Issue by bakman2** [lokenx/plexrequests-meteor#63]
too bad it is written in meteor. 
majority of users will have problems/or cannot/will not run this.

**Comment by lokenx** [comment]
Thank for the constructive feedback. We haven't had many people complain about issues that weren't straightforward to fix or complaints about not wanting to run Meteor. There is a [Django/Python](https://github.com/lokenx/plexrequests) version that I originally started you can use for Movie requests if you'd like. Otherwise, feel free to fork it and write it in whatever language/framework/platform you prefer!
