### ISSUE TITLE
[Request] Report a Problem with a Movie or TV Show

### ISSUE THREAD

**Issue by RandomNinjaAtk** [lokenx/plexrequests-meteor#67]
I was advised to post this here, anyways...

The general idea would be for a way that Users can report a problem with a particular movie, this doesn't have to be anything fancy...

A user could search for the title of the movie that their having an issue with and with a simple 3 button menu for choices, they could report the movie as having an issue such as: Miss Identified, Wrong Audio Language, No subtitles, Doesn't Play

Because using this amazing tool along with other tools to fully automate everything, there are bound to be times where you get something that doesn't match what it was supposed to be or has some other minor issue.

This would be a way for the users to report this to the Plex admin so he can further investigate and hopefully resolve the problem. Currently there is no way to do this or track it and it requires end users to just contact you via other means. This would greatly simplify the communication. There are probably ways that this could be automated to tell it to find an alternate release, like using couchpotato.

However, I would just simply be happy with a notification and a list of all reported issues. The second step would be finding a way to automate. This way not only the users could request content, but they could act as a verification/auditor of said content....

Just some thoughts!!

Edit: I think this was previously posted to the wrong GIT project, so posting here

**Comment by lokenx** [comment]
I've been thinking of ways to do that are the least "need to re-write the whole thing" and currently have none that come to mind.

We could add another button next to `add` that says `report` problem, I'm just not sure how to get this info to the admin. I don't want to make people use the houston admin interface to view this information (although obviously it will be there because it will have to be saved in the DB). It could be just a new page `/issues` or something that they can visit and see reported issues/mark as solved.

OK I have some ideas that aren't too bad, although it would require a new collection. Regarding the automation part of things, I'm not familiar enough of CP/SR/SO to know how they would handle things like this.

**Comment by RandomNinjaAtk** [comment]
Yeah, the whole automation part of it is a long term goal. A simple page with reported issues, like the list you provide of requested movies would do fine.

My only suggestion would be to at least give the reporting option a few sub options to choose from. So that way it gives the admin a reason to why it was reported. They can be canned choices, like:

- No subtitles for foreign language parts
- Audio is in the wrong native language
- Video does not play (those times you get an early release that is a fake)
- Wrong Movie (Movie title/artwork does not match the movie played)

These would clue the Admin to further investigate and resolve the issue. Obviously like the audio is in the wrong language would be determined by the admin. I really only speak english, but say a title only has french audio, I would like to be notified, that a film or title does not have english audio so I can remove it....

Just some more thoughts

**Comment by pmow** [comment]
This would be great to have.

**Comment by lokenx** [comment]
It's on the map, busy cleaning up a new admin interface that this will be part of eventually.

**Comment by lokenx** [comment]
Added in v0.6. Currently includes a few basic options, will add more as needed.

- Wrong audio
- No subtitles
- Wrong content
- Playback issues
