### ISSUE TITLE
[Request] Multiple Couchpotato servers

### ISSUE THREAD

**Issue by Mirabis** [lokenx/plexrequests-meteor#70]
Would it be possible to send the requests to multiple Couchpotato servers?
Unfortunately CP doesn't handle 3D very well with categories, thus some users install two intances of CP :)

**Comment by lokenx** [comment]
How would you see us differentiating between what goes to which server? Sorry, but I don't see this being implemented, but let me know your thoughts!

**Comment by Mirabis** [comment]
Well in this particular case it  should go to both servers, as one handles 3D and the other 2D.

2D = hostname/couchpotato/
3D = hostname/couchpotato3d/

Alternatively, if one would like to pick ~ a button with [3D] or [2D] could be added.
 * With those buttons one might as well set a category on a single CP instance as well - to differentiate between a 3D / 2D movie.

**Comment by RandomNinjaAtk** [comment]
I could see using this myself....

**Comment by lokenx** [comment]
@RandomNinjaAtk would you also use it in the sense that requests go to both servers?

For sending requests to both servers that is straight forward to do. However, I can see it being a rather niche use case as well as adding a secondary CP entry could confuse people. What if I made a new branch, in sync with either `dev` or `master`, and added this functionality. Those that want multiple CP servers can then clone that branch instead of main two.

Let me know your thoughts!

**Comment by Mirabis** [comment]
Seperate branch would be fine for me : )

**Comment by RandomNinjaAtk** [comment]
I would only have the second instance setup for 3d movies, so it probably wouldn't matter if it went to both because the categories and etc would force only 3d movies.

The problem with having only one instance of CP and want both 2d and 3d, is that CP will overwrite the 2d file with the 3d file. Currently there is no way to keep both in CP. Also it helps for Plex's case because you create a second library with 3d movies only.

**Comment by Jeradin** [comment]
I think it would be better to push [CP](https://github.com/RuudBurger/CouchPotatoServer) have better 3D handling.

Mine works pretty well with  [these settings](https://github.com/RuudBurger/CouchPotatoServer/issues/3245#issuecomment-43151052).

**Comment by Mirabis** [comment]
Well, having two instances is working now - 3D support has been on 'to-do' for quite a while... So I rather have something working sooner than later ^^?

**Comment by lokenx** [comment]
Started a branch for you guys [here](https://github.com/lokenx/plexrequests-meteor/tree/two-cp-servers). It's very rudimentary right now. There isn't a test page for the second one and it won't update movie status from the second server. Wasn't sure the best way how to handle that with two servers so it just ignores it for now: with the assumption that not everything will have 3D movies but even for 3D ones you will still download a regular 2D version. You may see weird things when adding the movie if you're viewing the status a movie as you add it but that's just because it goes through the motions twice. Also, the you need to have a CP server setup in the first slow, because the second one does not add it to the db.

**Comment by lokenx** [comment]
Is this still a wanted feature? There isn't a version inline with v0.6 because I forgot this was a thing. Please let me know, or I shall close the ticket.

**Comment by Mirabis** [comment]
I still use two couchpotato instances, but haven't been using plex request for a while :(.... Wanted a subdirectory reverse proxy xD 

I love that we can add 2 on this branch, because couchpotato kind of requires 2 instances for 2D and 3D

**Comment by lokenx** [comment]
Ah no worries! Why the sub-directory desire? What's wrong with a sub-domain?

**Comment by unixjeff** [comment]
As long as you have  apache or nixg you can set up a reverse proxy to do subdirectory or subdomain

**Comment by lokenx** [comment]
People were having issues, #88 

Not sure if it's of how Meteor works or if I did something but I'll look at it after the new release in more depth.

**Comment by lokenx** [comment]
Thought: what if there was second request button for movies called `Request 3D` or something in addition to the regular request button? Or do you want 3D and regular copies? What if there isn't a 3D version?

**Comment by Mirabis** [comment]
If there's no 3D version it will keep on searching forever :package: 

Couchpotato doesn't check that :(

**Comment by lokenx** [comment]
So how do you handle that now? Or do you just leave it search and delete when you get around to it?
		
        
		
		 ---- On Tue, 27 Oct 2015 20:41:47 -0400  notifications@github.com  wrote ----If there's no 3D version it will keep on searching forever  
Couchpotato doesn't check that :(

**Comment by Mirabis** [comment]
I just let it search and delete once every few months

**Comment by Noktam** [comment]
I have the same issue with multiple sickrage.
(One of the sickrage is for french content, the other one is for english content)
