### ISSUE TITLE
[Sonarr] "Couldn't evaluate decision" on series search

### ISSUE THREAD

**Issue by whitecollar17** [lokenx/plexrequests-meteor#79]
Since the last commits i have troubles with adding a serie into Sonarr.
I have this problem only when i add a serie through plex requests. When i add a serie into sonarr, i didn't have this problem.

After i add a serie and choose the option "All episodes" i get the following errors in sonarr when i do a manual search for the serie:

Message
Couldn't evaluate decision on XXXXX.S02E15.PROPER.DVDRip.XviD-REACTOR: De objectverwijzing is niet op een exemplaar van een object ingesteld.
Exception
System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij NzbDrone.Core.DecisionEngine.Specifications.QualityAllowedByProfileSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\DecisionEngine\Specifications\QualityAllowedByProfileSpecification.cs:regel 21
   bij NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:regel 123

**Comment by lokenx** [comment]
So Sonarr is having issues searching for shows? Could you per chance translate the first couple lines of Dutch (been years since I spoke it)? Something about it being undefined object?

Does a search for similar type of error message with Sonarr itself turn anything up? What if you add series using the other option, new episodes only? Is it all shows, or just certain?

I feel like it's something to do with maybe the quality settings, what qualityProfileID are you using?

**Comment by whitecollar17** [comment]
Hi Lokenx,

Its dutch ;) The translation:
"Object reference not set to an instance of an object"

 I didn't find something what i can use to solve the problem.
My qualityProfileID setting is now "1".
But I do not know what it stands for.
maybe its that the reason why i doesn't work :P

**Comment by lokenx** [comment]
Thought so! Can you tr a different number, say 2 or 3? When looking at the details of a TV show added through Plex Requests versus through Sonarr is anything different that you can see?

**Comment by whitecollar17** [comment]
I change it to "3", same problem. What does qualityProfileID?
After Adding the tv show in plex requests i can't open it in sonarr. Its gives me a 404 error.
I need to f5 a lot of times to see it also sonarr

**Comment by whitecollar17** [comment]
Lokenx, i found the problem.
it is possible that the option Series Type 'm not assigned?
When I manually change this option and back again and then search again i don't get this problem

**Comment by Foebik** [comment]
@whitecollar17 
QUOTE: After Adding the tv show in plex requests i can't open it in sonarr. Its gives me a 404 error. (funny 404 error btw)

This is something that Sonnar does (and SB/SR too I think), refreshing the browser resolves this. Not sure why you have to do it a lot though. That's a bit weird.

**Comment by lokenx** [comment]
Yes, if you have Sonarr open when you're adding TV series (as well as SickRage) it will look like it's failed or having issues mainly because it hasn't loaded everything yet. Typically, you give it a few seconds (more if it's a big show with many seasons) and refresh the page and it should be fine.

Can you try adding a show without Sonarr open, then go and open Sonarr 30 seconds later and see what it does? It's possible you're trying the manual search while the show is still being loaded up.

**Comment by lokenx** [comment]
Closing, if it's still an issue, please let me know!
