### ISSUE TITLE
[Request] User Request Restrictions

### ISSUE THREAD

**Issue by GleDel** [lokenx/plexrequests-meteor#80]
Would it be possible to add a feature where you can restrict the maximum amount of movies / tv-shows a user can demand?

The restriction could be user based or it could be for all users. 

For example: 

All users can demand 5 movies a week and 1 tv-show each month except for one or two users who have no restriction at all.

**Comment by lokenx** [comment]
Thanks for opening an issue! This has been brought up and will be evaluated for inclusion. Main issue on how best to keep track of requests but it's on the list!

**Comment by Foebik** [comment]
Just a thought, if you are forcing the users to actually use their Plex logins, the you can track that fairly reliably I would think. But if you don't use that option (let them make up whatever, whenever) then it wouldn't work out so well. But if that's the case the option would just be unavailable.

**Comment by lokenx** [comment]
I've added a basic user limit for Movies only (haven't looked at it regarding the season selection modal yet) that can be set in `/admin`. Please give it a go! I'll be changing it to so that if you set it to 0 there is no limit. Also keep in mind it's a limit for ALL users, including the admin user (an exception will be added for them later).

Added in commit 130d6e1791fdda26bc411095ccd362627b2bb8e3 or version 0.5.4 on DEV branch

**Comment by lokenx** [comment]
TV show limit added as well!
