### ISSUE TITLE
[Request] Requests details improvement

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#93]
when viewing the request i would like to see a legend that says in "done" column green check means completed cloud with arrow down means in-progress. also i think the column should be named status instead of done
![plex requests](https://cloud.githubusercontent.com/assets/751756/8538297/5eb8f38e-2438-11e5-9d0f-1d37cb6e5c71.jpg)

**Comment by lokenx** [comment]
Thoughts anyone? I'm not entirely against either change, I'm just not sure how/where to provide this information or if it's worth the additional visual clutter.

**Comment by unixjeff** [comment]
When I visualized it I see it horizontally to the left of the filter box

**Comment by Jeradin** [comment]
I like the idea of changing the column header to "Status". Legend wise, maybe just a hover tooltip? clean and easy.

**Comment by lokenx** [comment]
I'm not sure about the content of the overlay. This is just using vanilla HTML title attribute. Bootstrap has more complex tooltip abilities but because the table is generated I'm not sure if we can pass that variable through for the title.

Alternatively, could put a question mark/help icon somewhere which opens a modal dialog with a legend.

<img width="476" alt="status overlay" src="https://cloud.githubusercontent.com/assets/10313292/8578797/dde992e8-257e-11e5-9d0d-e93080f32782.png">

**Comment by Jeradin** [comment]
Ya, that is too much, will be annoying with them popping up everything someone scrolls across them.

I think the symbols should really tell their own function personally. 

IF they are added, I would say super simple 1 to 2 works.
“Looking”
“Downloaded"



On July 8, 2015 at 12:37:40 PM, loken (notifications@github.com) wrote:

I'm not sure about the content of the overlay. This is just using vanilla HTML title attribute. Bootstrap has more complex tooltip abilities but because the table is generated I'm not sure if we can pass that variable through for the title.

Alternatively, could put a question mark/help icon somewhere which opens a modal dialog with a legend.

**Comment by unixjeff** [comment]
Not sure if it possible by I would like a failed/unable to find icon so if it can't complete the reason is known

**Comment by lokenx** [comment]
> Not sure if it possible by I would like a failed/unable to find icon so if it can't complete the reason is known

We get the status from Couch Potato, and it doesn't provide that via the method we're looking--possibly not at all. It may be a different API call but haven't looked.

**Comment by lokenx** [comment]
Well, if want more descriptive icons please feel free to pick something else! Font Awesome is loaded so if it's from them that would be simplest.

http://fortawesome.github.io/Font-Awesome/icons/

@Jeradin You thinking overlays for each status image that says "looking"/"downloaded"? So it would pop up for every line?

I personally like the modal idea, just unsure where to place an icon/text to open it.

**Comment by lokenx** [comment]
Regarding the tool tip, I think if I add one to the actual icons (as in one for downloaded, and one for searching) that should be fine ("Downloaded", "Searching"). Anymore granular details requires multiple CP calls, and comparing release date to found releases etc isn't worth the slight difference in information.

**Comment by lokenx** [comment]
Closing as this doesn't apply in the new version.
