### ISSUE TITLE
[Request] UI Changes

### ISSUE THREAD

**Issue by pmow** [lokenx/plexrequests-meteor#96]
Please realize this is just one person's opinion and in design there is no "right" answer.  That being said I thought I'd write down what I immediately thought when using the web app:

1. Negative space on all sides.  There's a hidden button to show the request lists, I would leave the lists shown (left for movies, right side for TV) and have request form in the middle.
2. The categories don't look like buttons, at the very least a line between them.
3. The textbox can be shown always, but disabled until a category is selected.
4. Making the text configurable would be good to provide links, contact details, etc.  Strictly speaking the user isn't doing a TMDB search, the website is.

**Comment by lokenx** [comment]
No worries!

1. I'm using Bootstrap for base styling and the grid and that's just how it's spacing works unless I do full width (which I don't think would look good). Combining both lists into one would make it excessively wide. But feel free to try and mock something up.
2. That is true and has been bugging me, haven't gotten around to "fixing"
3. Similar to above
4. Fair point, could look into making the field a markdown editable text.

But first priority is finding time to finish admin interface @Jeradin started!

**Comment by Foebik** [comment]
I think one of the points has some merit.

"There's a hidden button to show the request lists, I would leave the lists shown"

I think at one point, hiding the list was desirable because it was just one massive list that could take a while to load and/or wasn't very pretty. But we have since moved to a row per page system. 

My two cents is, even if nothing else changes, you can get rid of the hide option. The only time hiding might be good is when a category hasn't been selected yet.

**Comment by lokenx** [comment]
1. No longer applies to v0.6
2. Same, but maybe don't like new style either
3. It is!
4. Wording has changed, configuring could be added later if there's request for it.
